backend:
  name: github
  repo: keramei/test-gatsby-site

publish_mode: editorial_workflow
media_folder: static/assets
public_folder: assets/

collections:
- name: illustration
  label: Illustration
  folder: works/illustrations
  create: true
  slug: "{{slug}}"
  fields: &works_fields
  - { name: cover, label: "Cover Image", widget: image }
  - { name: title, label: Title, widget: string }
  - { name: order, label: "Sort Order", widget: number, valueType: int, default: 999}
  - { name: body, label: Body, widget: markdown }
- name: sequential
  label: Sequential
  folder: works/sequential
  create: true
  slug: "{{slug}}"
  fields: *works_fields
- name: study
  label: Study
  folder: works/studies
  create: true
  slug: "{{slug}}"
  fields: *works_fields
- name: pages
  label: Pages
  files:
    - label: About Page
      name: about
      file: content/about.md
      fields: *works_fields
