backend:
  name: github
  repo: keramei/test-gatsby-site

publish_mode: editorial_workflow
media_folder: static/assets

collections:
- name: illustration
  label: Illustration
  folder: works/illustrations
  create: true
  slug: "{{slug}}"
  fields: &works_fields
  - { name: title, label: Title, widget: string }
  - name: images
    label: Images
    widget: list
  - { name: body, label: Body, widget: markdown }
- name: narrative
  label: Narrative
  folder: works/narratives
  create: true
  slug: "{{slug}}"
  fields: *works_fields
- name: study
  label: Study
  folder: works/studies
  create: true
  slug: "{{slug}}"
  fields: *works_fields
- name: pages
  label: Pages
  files:
    - label: About Page
      name: about
      file: content/about.md
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Body, name: body, widget: markdown}
